### ISSUE TITLE
Unit test failing in pkg/lint

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1013]
```
=== RUN   TestInvalidYaml
2016/08/01 13:11:12 Preparing template albatross/templates/_helpers.tpl
2016/08/01 13:11:12 Preparing template albatross/templates/svc.yaml
--- FAIL: TestInvalidYaml (0.01s)
	lint_test.go:66: All didn't fail with expected errors, got []support.Message(nil)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 20 [running]:
panic(0x45efc0, 0xc8200100d0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3ff
testing.tRunner.func1(0xc8200cc630)
	/usr/local/Cellar/go/1.6.2/libexec/src/testing/testing.go:467 +0x22a
panic(0x45efc0, 0xc8200100d0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x521
k8s.io/helm/pkg/lint.TestInvalidYaml(0xc8200cc630)
	/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/lint/lint_test.go:68 +0x2be
testing.tRunner(0xc8200cc630, 0x6cf158)
	/usr/local/Cellar/go/1.6.2/libexec/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/Cellar/go/1.6.2/libexec/src/testing/testing.go:582 +0xae3
FAIL	k8s.io/helm/pkg/lint	0.053s
```

**Comment by technosophos** [comment]
Update: I tried running the test in a loop. While I didn't get an error, the output was confusing. Looks like the templates might not always be loaded:

```console
$  for i in {1..20}; do go test -v -run TestInvalidYaml ./pkg/lint; done 
=== RUN   TestInvalidYaml
2016/08/01 17:06:16 Preparing template albatross/templates/_helpers.tpl
2016/08/01 17:06:16 Preparing template albatross/templates/fail.yaml
--- PASS: TestInvalidYaml (0.00s)
PASS
ok  	k8s.io/helm/pkg/lint	0.014s
=== RUN   TestInvalidYaml
2016/08/01 17:06:17 Preparing template albatross/templates/fail.yaml
--- PASS: TestInvalidYaml (0.00s)
PASS
ok  	k8s.io/helm/pkg/lint	0.014s
=== RUN   TestInvalidYaml
2016/08/01 17:06:18 Preparing template albatross/templates/svc.yaml
2016/08/01 17:06:18 Preparing template albatross/templates/_helpers.tpl
2016/08/01 17:06:18 Preparing template albatross/templates/fail.yaml
--- PASS: TestInvalidYaml (0.00s)
PASS
ok  	k8s.io/helm/pkg/lint	0.014s
=== RUN   TestInvalidYaml
2016/08/01 17:06:20 Preparing template albatross/templates/_helpers.tpl
2016/08/01 17:06:20 Preparing template albatross/templates/fail.yaml
--- PASS: TestInvalidYaml (0.00s)
PASS
ok  	k8s.io/helm/pkg/lint	0.013s
=== RUN   TestInvalidYaml
2016/08/01 17:06:21 Preparing template albatross/templates/_helpers.tpl
2016/08/01 17:06:21 Preparing template albatross/templates/fail.yaml
--- PASS: TestInvalidYaml (0.00s)
PASS
ok  	k8s.io/helm/pkg/lint	0.013s
```

**Comment by technosophos** [comment]
Alright, I can see why the files it tests are non-deterministic. It pulls the files out of a map, and processing will stop as soon as `fail.yaml` is parsed. I cannot yet reproduce the case where the other two files are evaluated, but `fail.yaml` is skipped.

**Comment by technosophos** [comment]
I ran 4,000 iterations of `TestInvalidYaml` and could not reproduced. So I'll leave this here, but I can't find the cause.

**Comment by technosophos** [comment]
After lots and lots of testing, I cannot reproduce this. Closing. Re-open if you can reproduce it.
