### ISSUE TITLE
Helm list crashes tiller if there are other configmaps inside the kube-system namespace

### ISSUE THREAD

**Issue by Chronojam** [kubernetes/helm#1115]
As above, dont think its a clone of #1083 due to this crashing when a configmap *is* present

```
$ helm init
$HELM_HOME has been configured at $HOME/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!

$ helm list # No Output
$ cat ~/ingress-uid-replace.yaml 
apiVersion: v1
data:
  uid: 6665423234b000
kind: ConfigMap
metadata:
  name: ingress-uid
  namespace: kube-system

$ kubectl create -f ~/ingress-uid-replace.yaml
configmap "ingress-uid" created

$ helm list
2016/08/26 17:20:07 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing

$ kubectl logs tiller-deploy-610593871-1qgas --namespace=kube-system

Tiller is running on :44134
Tiller probes server is running on :44135
Storage driver is ConfigMap
2016-08-26 16:20:06.582004 I | Listing all releases with filter
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40826e]

goroutine 33 [running]:
panic(0x1472be0, 0xc42000a030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*releaseServer).ListReleases.func1(0xc4202ea540, 0x14af540)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:79 +0x1e
k8s.io/helm/pkg/storage.All.func1(0xc4202ea540, 0xc4203177e0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/filter.go:51 +0x59
k8s.io/helm/pkg/storage.FilterFunc.Check(0xc4203177e0, 0xc4202ea540, 0x1)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/filter.go:30 +0x35
k8s.io/helm/pkg/storage.(*Storage).ListFilterAll.func1(0xc4202ea540, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:94 +0x5a
k8s.io/helm/pkg/storage/driver.(*ConfigMaps).List(0xc420443540, 0xc4203169a0, 0x1, 0x13d1ee0, 0xc420443d00, 0x0, 0xc420499b00)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/driver/cfgmaps.go:108 +0x282
k8s.io/helm/pkg/storage.(*Storage).ListFilterAll(0xc420443570, 0xc420022310, 0x1, 0x1, 0x0, 0x0, 0xc420304178, 0x16be4b6, 0xc420304178)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:95 +0x10d
main.(*releaseServer).ListReleases(0xc420022030, 0xc4201783c0, 0x1e950a0, 0xc420443cc0, 0x0, 0xc420020cd0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:84 +0xf3
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_ListReleases_Handler(0x15886e0, 0xc420022030, 0x1e937e0, 0xc420304100, 0x0, 0xc420024400)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:523 +0x117
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420448000, 0x1e951c0, 0xc4200815f0, 0xc4200761c0, 0xc42033d5a0, 0x1eb06e0, 0xc42018a0c0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:575 +0x22a
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420448000, 0x1e951c0, 0xc4200815f0, 0xc4200761c0, 0xc42018a0c0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:650 +0xc33
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420443a90, 0xc420448000, 0x1e951c0, 0xc4200815f0, 0xc4200761c0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:323 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:324 +0xa3
```

Cheers

Helm version v2.0.0-alpha.3

**Comment by technosophos** [comment]
Is this on GKE?

**Comment by Chronojam** [comment]
It is yeah, I just tested it on minikube cluster - but got the same result

**Comment by adamreese** [comment]
For cause/fix/workaround: https://github.com/kubernetes/helm/issues/1083#issuecomment-243520610
