### ISSUE TITLE
SIGSEGV: segmentation violation thrown when doing 'helm list'

### ISSUE THREAD

**Issue by spiddy** [kubernetes/helm#1195]
# Problem

Scenario: I have an old version of helm installed on my system (`v2.0.0-alpha.3`) and I want to initialize `tiller` on the cluster. So I do the following:

```
➜  ~ helm version
v2.0.0-alpha.3
➜  ~ helm init
$HELM_HOME has been configured at $HOME/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
```

Once `tiller` is installed I get the following error when trying to do `helm list`:

```
➜  ~ helm list
2016/09/14 10:28:36 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
```

On server side I get the following:

```
Tiller is running on :44134
Tiller probes server is running on :44135
Storage driver is ConfigMap
2016-09-14 08:29:21.792813 I | Listing all releases with filter
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4092ae]

goroutine 35 [running]:
panic(0x1478860, 0xc42000a030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*releaseServer).ListReleases.func1(0xc4202e8620, 0x14b5140)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:87 +0x1e
k8s.io/helm/pkg/storage.All.func1(0xc4202e8620, 0xc42022b920)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/filter.go:51 +0x59
k8s.io/helm/pkg/storage.FilterFunc.Check(0xc42022b920, 0xc4202e8620, 0x1)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/filter.go:30 +0x35
k8s.io/helm/pkg/storage.(*Storage).ListFilterAll.func1(0xc4202e8620, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:95 +0x5a
k8s.io/helm/pkg/storage/driver.(*ConfigMaps).List(0xc42044b840, 0xc42022aa80, 0x1, 0x13d7460, 0xc420410110, 0x0, 0xc4200cbb00)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/driver/cfgmaps.go:103 +0x282
k8s.io/helm/pkg/storage.(*Storage).ListFilterAll(0xc42044b850, 0xc420022328, 0x1, 0x1, 0x0, 0x2, 0xc420238378, 0x16c528e, 0xc420238378)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:96 +0x10d
main.(*releaseServer).ListReleases(0xc420022030, 0xc4201783c0, 0x1e9e120, 0xc4204100f0, 0x0, 0xc4200214d0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:92 +0xf3
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_ListReleases_Handler(0x1597480, 0xc420022030, 0x1e9c860, 0xc420238300, 0x0, 0x1ecd400)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:529 +0x117
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc42045c000, 0x1e9e180, 0xc42007f8c0, 0xc4200761c0, 0xc42004cd00, 0x1eb97e0, 0xc420184420, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:575 +0x22a
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42045c000, 0x1e9e180, 0xc42007f8c0, 0xc4200761c0, 0xc420184420)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:650 +0xc33
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42044bfe0, 0xc42045c000, 0x1e9e180, 0xc42007f8c0, 0xc4200761c0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:323 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:324 +0xa3
```

Going through the system I can see that `helm v2.0.0-alpha.3` installed `canary` release on the cluster.

```
➜  ~ kubectl describe pod -l name=tiller --namespace=kube-system|grep Image:
    Image:			gcr.io/kubernetes-helm/tiller:canary
```

This creates incompatibility issues between server/client.

# Hotfix

In order to override this, first cleanup the `canary` release:

```
➜  ~ kubectl delete deployment tiller-deploy --namespace=kube-system
deployment "tiller-deploy" deleted
```

And then install using a custom image:

```
➜  ~ helm init -i gcr.io/kubernetes-helm/tiller:v2.0.0-alpha.3
$HELM_HOME has been configured at $HOME/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
➜  ~ helm list
➜  ~
```

# Proposal

`helm init` command should install the immutable compatible version of helm client (e.g. `v2.0.0-alpha.3`), instead of `canary` release in order to avoid incompatibilities between server/client.

Server tiller upgrade process should also be discussed. Maybe add `-f` flag for force install the new deployment when new releases are out.

**Comment by spiddy** [comment]
That is already resolved in `v2.0.0-alpha.4`.

Closing

**Comment by spiddy** [comment]
Talked too soon.

Ok the immutable version is resolved, but the segmentation fault is still persistent.

I get the same error as before with the `v2.0.0-alpha.4` as with `canary` release.

I'm now using helm `v2.0.0-alpha.4` client and `v2.0.0-alpha.4` server and I get the same segmentation fault as above.

I'll rename the issue to clarify the problem.

anyone else has this issue?

**Comment by technosophos** [comment]
See also #1173

**Comment by fibonacci1729** [comment]
fixed by #1207

**Comment by spiddy** [comment]
cool.

Until final release, the workaround is to use `canary` build:

```
helm init -i gcr.io/kubernetes-helm/tiller:canary
```

**Comment by philips** [comment]
Seems like we should do a release just so people who are testing don't continue to hit it.
