### ISSUE TITLE
Bug: Tiller segmentation fault on `helm list`

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#1209]
I get a segmentation fault when I do `helm list` in a cluster I have setup in GKE. It seems to work fine in Minikube though.

In the Client
```bash
helm list
2016/09/15 16:49:58 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
```

In Tiller:
```go
ubectl logs tiller-deploy-1979772362-pc65r --namespace kube-system -f                                   
Tiller is running on :44134
Tiller probes server is running on :44135
Storage driver is ConfigMap
2016-09-15 23:49:57.337949 I | Listing all releases with filter
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x408c6e]

goroutine 37 [running]:
panic(0x1473dc0, 0xc42000a030)
        /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
main.(*releaseServer).ListReleases.func1(0xc4202ea700, 0x14b06a0)
        /Users/adamreese/p/go/src/k8s.io/helm/cmd/tiller/release_server.go:87 +0x1e
k8s.io/helm/pkg/storage.All.func1(0xc4202ea700, 0xc42030fc60)
        /Users/adamreese/p/go/src/k8s.io/helm/pkg/storage/filter.go:51 +0x59
k8s.io/helm/pkg/storage.FilterFunc.Check(0xc42030fc60, 0xc4202ea700, 0x1)
        /Users/adamreese/p/go/src/k8s.io/helm/pkg/storage/filter.go:30 +0x35
k8s.io/helm/pkg/storage.(*Storage).ListFilterAll.func1(0xc4202ea700, 0x0)
        /Users/adamreese/p/go/src/k8s.io/helm/pkg/storage/storage.go:94 +0x5a
k8s.io/helm/pkg/storage/driver.(*ConfigMaps).List(0xc42043f580, 0xc42030eb20, 0x1, 0x13d2f80, 0xc4203fe0b0, 0x0, 0xc420497b00)
        /Users/adamreese/p/go/src/k8s.io/helm/pkg/storage/driver/cfgmaps.go:108 +0x282
k8s.io/helm/pkg/storage.(*Storage).ListFilterAll(0xc42043f590, 0xc420022338, 0x1, 0x1, 0x0, 0x2, 0xc4202fc578, 0x16bf886, 0xc4202fc578)
        /Users/adamreese/p/go/src/k8s.io/helm/pkg/storage/storage.go:95 +0x10d
main.(*releaseServer).ListReleases(0xc420022030, 0xc420176460, 0x1e970a0, 0xc4203fe090, 0x0, 0xc420020cd0)
        /Users/adamreese/p/go/src/k8s.io/helm/cmd/tiller/release_server.go:92 +0xf3
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_ListReleases_Handler(0x1592440, 0xc420022030, 0x1e957e0, 0xc4202fc500, 0x0, 0xc4203e5800)
        /Users/adamreese/p/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:529 +0x117
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420444000, 0x1e971c0, 0xc420081200, 0xc4200761c0, 0xc42033d560, 0x1eb2720, 0xc42018bc80, 0x0, 0x0)
        /Users/adamreese/p/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:575 +0x22a
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420444000, 0x1e971c0, 0xc420081200, 0xc4200761c0, 0xc42018bc80)
        /Users/adamreese/p/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:650 +0xc33
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42043feb0, 0xc420444000, 0x1e971c0, 0xc420081200, 0xc4200761c0)
        /Users/adamreese/p/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:323 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/adamreese/p/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:324 +0xa3
```

* I have deleted the `tiller-deploy` deployment and re-init and checked that it is using the image `gcr.io/kubernetes-helm/tiller:v2.0.0-alpha.4`. 
* I am using the latest version of helm and tiller from the master branch
* Regarding k8s, I am using 1.3.3 in server and 1.3.6 in client.

```go
kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3", GitCommit:"c6411395e09da356c608896d3d9725acab821418", GitTreeState:"clean", BuildDate:"2016-07-22T20:29:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:06:06Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by prydonius** [comment]
Fixed in #1207
