### ISSUE TITLE
Deleting release whose resources were manually deleted crashes Tiller

### ISSUE THREAD

**Issue by martinmaly** [kubernetes/helm#1374]
$ helm delete full-frog --purge
2016/10/14 11:11:27 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing

$ kubectl logs --namespace kube-system --previous tiller-deploy-637859184-lyanl
Tiller is running on :44134
Tiller probes server is running on :44135
Storage driver is ConfigMap
2016-10-14 18:11:27.040528 I | Getting deployed release from 'full-frog' history
2016-10-14 18:11:27.062318 I | uninstall: Deleting full-frog
2016-10-14 18:11:27.062525 I | Executing pre-delete hooks for full-frog
2016-10-14 18:11:27.062594 I | Hooks complete for pre-delete full-frog
2016-10-14 18:11:27.070361 I | info: manifest "manifest-0" is empty. Skipping.
2016-10-14 18:11:27.072351 I | Starting delete for full-frog-example
2016-10-14 18:11:27.072465 I | Using reaper for deleting full-frog-example
2016-10-14 18:11:27.074656 I | services "full-frog-example" not found
2016-10-14 18:11:27.075852 I | Starting delete for full-frog-example
2016-10-14 18:11:27.077766 I | configmaps "full-frog-example" not found
2016-10-14 18:11:27.079171 I | Starting delete for full-frog-example
2016-10-14 18:11:27.084079 I | Using reaper for deleting full-frog-example
2016-10-14 18:11:27.096703 I | deployments.extensions "full-frog-example" not found
2016-10-14 18:11:27.096838 I | Executing post-delete hooks for full-frog
2016-10-14 18:11:27.096908 I | Hooks complete for post-delete full-frog
2016-10-14 18:11:27.096949 I | Deleting release "full-frog" (v1) from storage
**panic: runtime error: invalid memory address or nil pointer dereference**
**[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5460fc]**

goroutine 48 [running]:
panic(0x1ac5960, 0xc42000a030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/pkg/storage/driver.(*ConfigMaps).Delete(0xc42040cb90, 0xc42062b6a0, 0xc, 0xc42062b6a0, 0xc, 0xc42038d2e0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/driver/cfgmaps.go:204 +0x13c
k8s.io/helm/pkg/storage.(*Storage).Delete(0xc42040cba0, 0xc42038d260, 0x9, 0x1, 0xc42038d260, 0x9, 0xc42038d2e0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:61 +0x160
main.(*releaseServer).UninstallRelease(0xc420022518, 0x7fedcf60a7c8, 0xc420465bf0, 0xc420a2ac40, 0x0, 0xd, 0xd)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:880 +0x4d0
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UninstallRelease_Handler(0x1c5bea0, 0xc420022518, 0x7fedcf60a7c8, 0xc420465bf0, 0xc42019cdc0, 0x0, 0x0, 0x0, 0x5064315554464555, 0x674143494b516b55)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:765 +0x27d
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4201a23c0, 0x2872400, 0xc420378bd0, 0xc4203a40f0, 0xc42010f110, 0x289de00, 0xc420465b00, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:608 +0xc50
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4201a23c0, 0x2872400, 0xc420378bd0, 0xc4203a40f0, 0xc420465b00)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:766 +0x6b0
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42038c5d0, 0xc4201a23c0, 0x2872400, 0xc420378bd0, 0xc4203a40f0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:419 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:420 +0xa3

---

$ helm version
Client: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"a324146945c01a1e2dd7eaf23caf0e55fabfd3d2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"4de5c4aa578ed9ca173aff472f00d2167ec59a88", GitTreeState:"dirty"}

**Comment by technosophos** [comment]
Thanks. Had you manually deleted the release configmap, too? Or just the resources it created?

**Comment by martinmaly** [comment]
Hmm ... I may have run something like

kubectl delete deployments,services,pods,configmaps --all
