### ISSUE TITLE
running helm inspect values with no options panics

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#1429]
```
╰─± helm inspect values
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x10ff880, 0xc420014100)
       	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
main.newInspectCmd.func2(0xc4200a3b00, 0x1bbdba0, 0x0, 0x0, 0x0, 0x0)
       	/Users/adamreese/p/go/src/k8s.io/helm/cmd/helm/inspect.go:91 +0x10f
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200a3b00, 0x1bbdba0, 0x0, 0x0, 0xc4200a3b00, 0x1bbdba0)
       	/Users/adamreese/p/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:571 +0x234
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200a2480, 0x0, 0x0, 0x0)
       	/Users/adamreese/p/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:661 +0x367
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200a2480, 0x1b53720, 0xc4200001a0)
       	/Users/adamreese/p/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:620 +0x2b
main.main()
       	/Users/adamreese/p/go/src/k8s.io/helm/cmd/helm/helm.go:110 +0x2d
```

**Comment by technosophos** [comment]
With a quick glance at the code, it appears that `helm inspect chart` may also have this problem. Someone needs to add `checkArgsLength` to those two `RunE` calls in `cmd/helm/inspect.go`.
