### ISSUE TITLE
helm does not want to install

### ISSUE THREAD

**Issue by Masber** [kubernetes/helm#1833]
Hi,

I am using kubeadm and I am having difficulties trying to deploy/run helm.

kubernetes version 1.5.1
```
[root@kub1 openstack-helm]# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

helm version 
```
[root@kub1 openstack-helm]# helm version
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Error: cannot connect to Tiller
```

pods
```
[root@kub1 openstack-helm]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
kube-system   calico-etcd-n091c                          1/1       Running   1          26m
kube-system   calico-node-1t9f5                          2/2       Running   4          26m
kube-system   calico-node-dk3hn                          2/2       Running   0          26m
kube-system   calico-policy-controller-807063459-v07cl   1/1       Running   2          26m
kube-system   dummy-2088944543-c3mf9                     1/1       Running   1          27m
kube-system   etcd-kub1.localhost                        1/1       Running   7          26m
kube-system   kube-apiserver-kub1.localhost              1/1       Running   7          27m
kube-system   kube-controller-manager-kub1.localhost     1/1       Running   1          14m
kube-system   kube-discovery-1769846148-ts199            1/1       Running   1          27m
kube-system   kube-dns-2924299975-48p4m                  4/4       Running   7          27m
kube-system   kube-proxy-g1j0j                           1/1       Running   0          26m
kube-system   kube-proxy-hwkt2                           1/1       Running   1          27m
kube-system   kube-scheduler-kub1.localhost              1/1       Running   2          27m
kube-system   tiller-deploy-3299276078-5kx5w             0/1       Running   1          41s
[root@kub1 openstack-helm]#
```
pod description
```
[root@kub1 openstack-helm]# kubectl describe pod tiller-deploy-3299276078-5kx5w -n kube-system
Name:           tiller-deploy-3299276078-5kx5w
Namespace:      kube-system
Node:           kub2.localhost/192.168.20.11
Start Time:     Thu, 19 Jan 2017 01:36:46 +1100
Labels:         app=helm
                name=tiller
                pod-template-hash=3299276078
Status:         Running
IP:             192.168.99.129
Controllers:    ReplicaSet/tiller-deploy-3299276078
Containers:
  tiller:
    Container ID:       docker://9ac08c4e29162901138605676004683c7ed22cfafe201935f1026723bd457720
    Image:              gcr.io/kubernetes-helm/tiller:v2.1.3
    Image ID:           docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:a5919b5a2a837fc265aeeb639413c653427332544c3a590bc8ed74370905d87a
    Port:               44134/TCP
    State:              Running
      Started:          Thu, 19 Jan 2017 01:38:27 +1100
    Last State:         Terminated
      Reason:           Error
      Exit Code:        2
      Started:          Thu, 19 Jan 2017 01:38:18 +1100
      Finished:         Thu, 19 Jan 2017 01:38:26 +1100
    Ready:              False
    Restart Count:      5
    Liveness:           http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:          http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9h4g9 (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  default-token-9h4g9:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-9h4g9
QoS Class:      BestEffort
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath           Type            Reason          Message
  ---------     --------        -----   ----                            -------------           --------        ------          -------
  1m            1m              1       {default-scheduler }                                    Normal          Scheduled       Successfully assigned tiller-deploy-3299276078-5kx5w to kub2.localhost
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Pulling         pulling image "gcr.io/kubernetes-helm/tiller:v2.1.3"
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Pulled          Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.1.3"
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Created         Created container with docker id 09867cb36ac1; Security:[seccomp=unconfined]
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Started         Started container with docker id 09867cb36ac1
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Killing         Killing container with docker id 09867cb36ac1: pod "tiller-deploy-3299276078-5kx5w_kube-system(8a2bb598-dd8b-11e6-8b84-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Created         Created container with docker id 0f2583248a73; Security:[seccomp=unconfined]
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Started         Started container with docker id 0f2583248a73
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Created         Created container with docker id 859dc48c4d12; Security:[seccomp=unconfined]
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Killing         Killing container with docker id 0f2583248a73: pod "tiller-deploy-3299276078-5kx5w_kube-system(8a2bb598-dd8b-11e6-8b84-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Started         Started container with docker id 859dc48c4d12
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Killing         Killing container with docker id 859dc48c4d12: pod "tiller-deploy-3299276078-5kx5w_kube-system(8a2bb598-dd8b-11e6-8b84-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Created         Created container with docker id aab68c3cfb4f; Security:[seccomp=unconfined]
  1m            1m              1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Started         Started container with docker id aab68c3cfb4f
  51s           51s             1       {kubelet kub2.localhost}        spec.containers{tiller} Normal          Killing         Killing container with docker id aab68c3cfb4f: pod "tiller-deploy-3299276078-5kx5w_kube-system(8a2bb598-dd8b-11e6-8b84-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  51s           35s             3       {kubelet kub2.localhost}                                Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 20s restarting failed container=tiller pod=tiller-deploy-3299276078-5kx5w_kube-system(8a2bb598-dd8b-11e6-8b84-0050568da433)"

  19s   19s     1       {kubelet kub2.localhost}        spec.containers{tiller} Normal  Started         Started container with docker id 6a8afb9e06e2
  19s   19s     1       {kubelet kub2.localhost}        spec.containers{tiller} Normal  Created         Created container with docker id 6a8afb9e06e2; Security:[seccomp=unconfined]
  11s   11s     1       {kubelet kub2.localhost}        spec.containers{tiller} Normal  Created         Created container with docker id 9ac08c4e2916; Security:[seccomp=unconfined]
  11s   11s     1       {kubelet kub2.localhost}        spec.containers{tiller} Normal  Killing         Killing container with docker id 6a8afb9e06e2: pod "tiller-deploy-3299276078-5kx5w_kube-system(8a2bb598-dd8b-11e6-8b84-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  1m    11s     5       {kubelet kub2.localhost}        spec.containers{tiller} Normal  Pulled          Container image "gcr.io/kubernetes-helm/tiller:v2.1.3" already present on machine
  10s   10s     1       {kubelet kub2.localhost}        spec.containers{tiller} Normal  Started         Started container with docker id 9ac08c4e2916
  51s   1s      4       {kubelet kub2.localhost}        spec.containers{tiller} Warning BackOff         Back-off restarting failed docker container
  1m    1s      8       {kubelet kub2.localhost}        spec.containers{tiller} Warning Unhealthy       Liveness probe failed: Get http://192.168.99.129:44135/liveness: dial tcp 192.168.99.129:44135: getsockopt: connection refused
  1m    1s      8       {kubelet kub2.localhost}        spec.containers{tiller} Warning Unhealthy       Readiness probe failed: Get http://192.168.99.129:44135/readiness: dial tcp 192.168.99.129:44135: getsockopt: connection refused
  1s    1s      1       {kubelet kub2.localhost}        spec.containers{tiller} Normal  Killing         Killing container with docker id 9ac08c4e2916: pod "tiller-deploy-3299276078-5kx5w_kube-system(8a2bb598-dd8b-11e6-8b84-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  1s    1s      1       {kubelet kub2.localhost}                                Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=tiller pod=tiller-deploy-3299276078-5kx5w_kube-system(8a2bb598-dd8b-11e6-8b84-0050568da433)"
```
can't see the logs and can't login to container...

any advise?

thank you very much

**Comment by technosophos** [comment]
If I were to take a guess, I'd guess that this has something to do with Tiller being able to authenticate to the Kube API server.

One thing you could try to do to debug is this:

1. Get the Tiller manifest: `helm init --dry-run --debug`
2. Modify the pod template for the deployment to do `command: ["/bin/sleep","9000"]` (right under `imagePullPolicy`)
3. Use `kubectl` to install this modified manifest, and then `kubectl exec` into the pod.

From there, you should be able to manually start Tiller and see if it starts correct or panics.

At least from there we will be able to gather some debugging info.

**Comment by Masber** [comment]
No luck
```
[root@kub1 ~]# helm init --dry-run --debug > tst.yaml
[root@kub1 ~]# kubectl create -f tst.yaml
error: unable to decode "tst.yaml": Object 'Kind' is missing in '{"metadata":{"creationTimestamp":null,"labels":{"app":"helm","name":"tiller"},"name":"tiller-deploy","namespace":"kube-system"},"spec":{"replicas":1,"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"helm","name":"tiller"}},"spec":{"containers":[{"image":"gcr.io/kubernetes-helm/tiller:v2.1.3","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/liveness","port":44135},"initialDelaySeconds":1,"timeoutSeconds":1},"name":"tiller","ports":[{"containerPort":44134,"name":"tiller"}],"readinessProbe":{"httpGet":{"path":"/readiness","port":44135},"initialDelaySeconds":1,"timeoutSeconds":1},"resources":{}}],"serviceAccountName":"","volumes":null}}},"status":{}}'

```

**Comment by iamzhout** [comment]
@Masber you can add below two lines at the begging tst.yaml, and try again.
```
apiVersion: extensions/v1beta1
kind: Deployment
```

**Comment by Masber** [comment]
thanks @iamzhout,

I did the changes, deployed the new manifest and `kubectl exec` the pod.

I then I run ./tiller but nothing happens, I can't see any output (and no log files).

```
[root@kub1 ~]# kubectl exec -it tiller-deploy-3934320834-7243p -n kube-system -- /bin/sh
/ # ls -al
total 49648
drwxr-xr-x   17 root     root          4096 Jan 19 22:21 .
drwxr-xr-x   17 root     root          4096 Jan 19 22:21 ..
-rwxr-xr-x    1 root     root             0 Jan 19 22:21 .dockerenv
-rwxr-xr-x    1 root     root             0 Jan 19 22:21 .dockerinit
-rw-rw-r--    1 root     root           646 Dec 22 21:03 Dockerfile
-rw-rw-r--    1 root     root           584 Dec 22 21:03 README.md
drwxr-xr-x    2 root     root          4096 Oct 18 18:58 bin
drwxr-xr-x    5 root     root           380 Jan 19 22:21 dev
drwxr-xr-x   13 root     root          4096 Jan 19 22:21 etc
drwxr-xr-x    2 root     root             6 Oct 18 18:58 home
drwxr-xr-x    5 root     root          4096 Oct 18 18:58 lib
lrwxrwxrwx    1 root     root            12 Oct 18 18:58 linuxrc -> /bin/busybox
drwxr-xr-x    5 root     root            41 Oct 18 18:58 media
drwxr-xr-x    2 root     root             6 Oct 18 18:58 mnt
dr-xr-xr-x  233 root     root             0 Jan 19 22:21 proc
drwx------    2 root     root            25 Jan 19 22:21 root
drwxr-xr-x    3 root     root            20 Jan 19 22:21 run
drwxr-xr-x    2 root     root          4096 Oct 18 18:58 sbin
dr-xr-xr-x   13 root     root             0 Jan 19 14:40 sys
-rwxrwxr-x    1 root     root      50803147 Dec 22 21:07 tiller
drwxrwxrwt    2 root     root             6 Oct 18 18:58 tmp
drwxr-xr-x    7 root     root            61 Oct 18 18:58 usr
drwxr-xr-x   10 root     root            93 Oct 18 18:58 var
/ # ./tiller
```

**Comment by iamzhout** [comment]
Maybe there are several points more to check:
1. Please try to start tiller with `./tiller --trace`, and run `helm version` again on master, to check if there are any console output 
2. what's the result for `kubectl get pods --all-namespaces` ?

**Comment by Masber** [comment]
Here it is:
```
[root@kub1 ~]# kubectl exec -it tiller-deploy-666958114-5lzmg -n kube-system -- /bin/sh
/ # ./tiller --trace
Cannot initialize Kubernetes connection: Get https://10.96.0.1:443/api: dial tcp 10.96.0.1:443: i/o timeoutpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x401a19]

goroutine 1 [running]:
panic(0x155bd80, 0xc420010030)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.start(0x201e620, 0xc4202ea2f0, 0x0, 0x1)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/tiller.go:93 +0x739
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0x201e620, 0xc42000a230, 0x1, 0x1, 0x201e620, 0xc42000a230)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x201e620, 0x0, 0x1708aa4, 0x12)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0x201e620, 0x2051144, 0x16f6045)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/tiller.go:80 +0x16c
/ # [root@kub1 ~]#
```

```
[root@kub1 ~]# helm version
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Error: cannot connect to Tiller
[root@kub1 ~]#
```

**Comment by iamzhout** [comment]
1. try to run command `env` and give results?
2. how about running `KUBERNETES_MASTER=10.96.0.1:8080 ./tiller --trace`

There is another issue: https://github.com/kubernetes/helm/issues/1280 also have similiar log, but the reporter says it is his cluster env problem, so not this case...

**Comment by Masber** [comment]
env
```
[root@kub1 ~]# kubectl exec -it tiller-deploy-666958114-z7v25 -n kube-system -- env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=tiller-deploy-666958114-z7v25
CALICO_ETCD_PORT_6666_TCP_PROTO=tcp
KUBERNETES_DASHBOARD_PORT_80_TCP_PROTO=tcp
KUBERNETES_DASHBOARD_PORT_80_TCP_PORT=80
KUBERNETES_DASHBOARD_PORT_80_TCP_ADDR=10.100.46.238
KUBE_DNS_PORT_53_UDP=udp://10.96.0.10:53
KUBE_DNS_PORT_53_UDP_PROTO=udp
KUBE_DNS_PORT_53_UDP_ADDR=10.96.0.10
KUBE_DNS_PORT_53_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT=443
KUBE_DNS_PORT_53_UDP_PORT=53
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBE_DNS_PORT=udp://10.96.0.10:53
KUBERNETES_DASHBOARD_SERVICE_PORT=80
KUBE_DNS_SERVICE_PORT_DNS_TCP=53
KUBERNETES_DASHBOARD_PORT=tcp://10.100.46.238:80
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBE_DNS_SERVICE_HOST=10.96.0.10
CALICO_ETCD_SERVICE_HOST=10.96.232.136
KUBERNETES_DASHBOARD_PORT_80_TCP=tcp://10.100.46.238:80
KUBERNETES_SERVICE_HOST=10.96.0.1
CALICO_ETCD_PORT_6666_TCP=tcp://10.96.232.136:6666
CALICO_ETCD_PORT_6666_TCP_PORT=6666
CALICO_ETCD_PORT_6666_TCP_ADDR=10.96.232.136
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBE_DNS_SERVICE_PORT=53
KUBE_DNS_SERVICE_PORT_DNS=53
KUBE_DNS_PORT_53_TCP_PORT=53
CALICO_ETCD_SERVICE_PORT=6666
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBE_DNS_PORT_53_TCP=tcp://10.96.0.10:53
KUBE_DNS_PORT_53_TCP_ADDR=10.96.0.10
CALICO_ETCD_PORT=tcp://10.96.232.136:6666
KUBERNETES_DASHBOARD_SERVICE_HOST=10.100.46.238
HOME=/root
```
telnet does not give output
```
[root@kub1 ~]# kubectl exec -it tiller-deploy-666958114-z7v25 -n kube-system -- telnet 10.96.0.1 443
[root@kub1 ~]#
```
However I can connect from the host:
```
[root@kub1 ~]# telnet 10.96.0.1 443
Trying 10.96.0.1...
Connected to 10.96.0.1.
Escape character is '^]'.

^CConnection closed by foreign host.
[root@kub1 ~]#
```

**Comment by iamzhout** [comment]
try this:

**Comment by Masber** [comment]
```
[root@kub1 ~]# kubectl get nodes
NAME             STATUS         AGE
kub1.localhost   Ready,master   15h
kub2.localhost   Ready          15h
[root@kub1 ~]# kubectl cluster-info
Kubernetes master is running at http://localhost:8080
KubeDNS is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[root@kub1 ~]# kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
[root@kub1 ~]#
```

I have 2 VMs running on VMWare with CentOS7
I followed the installation from the [website](https://kubernetes.io/docs/getting-started-guides/kubeadm/).
These are the steps I did to create the cluster:

1. Create repository and install software
```
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
setenforce 0
yum install -y docker kubelet kubeadm kubectl kubernetes-cni
systemctl enable docker && systemctl start docker
systemctl enable kubelet && systemctl start kubelet
```

2. Create master node
`kubeadm init`

3. Add worker
`kubeadm join --token=<token> <master-ip>` 

4. Install calico
`kubectl apply -f http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/kubeadm/calico.yaml`

5. Download Helm and install it
```
wget https://storage.googleapis.com/kubernetes-helm/helm-v2.1.3-linux-amd64.tar.gz
tar zxvf helm...
mv helm /usr/local/bin/helm
helm init
```

NOTE: I neither have created a proxy nor a cluster, etc.

**Comment by iamzhout** [comment]
Have you also installed calico addon on node(kube2)?

I myself use flannel network, and setup the k8s cluster on Ubuntu16.04 OS, everything is ok.

**Comment by Masber** [comment]
it looks like it works using flannel...
```
kube-system   tiller-deploy-3299276078-mxnv6           1/1       Running   0          3m        10.244.1.2      kub2.localhost
[root@kub1 ~]# kubectl logs tiller-deploy-3299276078-mxnv6 -n kube-system
Tiller is listening on :44134
Probes server is listening on :44135
Storage driver is ConfigMap
```

**Comment by technosophos** [comment]
@iamzhout Thanks for the detailed troubleshooting on that.

@Masber so are things good at this point?

**Comment by Masber** [comment]
No, I am still troubleshooting. I think I will have to open a case with calico...

**Comment by jfelten** [comment]
same issue here on Centos 7.3 using weaveworks as the network provider:
kubectl apply -f https://git.io/weave-kube

Will switch to flannel.

**Comment by technosophos** [comment]
Okay. If you don't mind keeping us updated... we're tracking this though we're not sure what we can do at this point.

**Comment by gajus** [comment]
> same issue here on Centos 7.3 using weaveworks as the network provider:
> kubectl apply -f https://git.io/weave-kube

Add me to the list of affected.

**Comment by jascott1** [comment]
@Masber @gajus Closing this due to inactivity. Please feel free to re-open if necessary.
