### ISSUE TITLE
`helm init` was completed but tiller status is Error

### ISSUE THREAD

**Issue by Ladicle** [kubernetes/helm#1931]
`helm init` was completed.
```
$ helm init
$HELM_HOME has been configured at $HOME/.helm.
Warning: Tiller is already installed in the cluster. (Use --client-only to suppress this message.)
Happy Helming!
```

But, the tiller pod status is Error.
```
$ kubectl get po -n kube-system tiller-deploy-3299276078-xm1pc
NAME                                    READY     STATUS    RESTARTS   AGE
tiller-deploy-3299276078-xm1pc          0/1       Error     19         1h
```

According to the log, connection refused error has occurred.
```
$ kubectl logs -n kube-system tiller-deploy-3299276078-xm1pc
Cannot initialize Kubernetes connection: Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refusedpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x401a19]

goroutine 1 [running]:
panic(0x155bd80, 0xc42000a030)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.start(0x201e620, 0x2051450, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/tiller.go:93 +0x739
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0x201e620, 0xc42000a250, 0x0, 0x0, 0x201e620, 0xc42000a250)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x201e620, 0x0, 0x1708aa4, 0x12)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0x201e620, 0x2051144, 0x16f6045)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/tiller.go:80 +0x16c
```

## Versions
* kubernetes
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
* helm
```
$ helm version
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Error: cannot connect to Tiller
```

**Comment by technosophos** [comment]
Tiller is unable to connect to the Kube API server. There's some discussion on that here: https://github.com/kubernetes/helm/blob/master/docs/install_faq.md

**Comment by Ladicle** [comment]
Thank you for your comment.
My k8s cluster is build by hyperkube. 
According to the log, tiller try to connect to localhost:8080.
Another normal tiller(not hyperkube) has connect to `kubernetes.default.svc.cluster.local.`.
Where does tiller get k8s api server address?

**Comment by Ladicle** [comment]
The caused was lack of rslave option of hyperkube.
https://github.com/kubernetes/kubernetes.github.io/pull/634
Therefore, Tiller pod can not generate token.
https://github.com/kubernetes/client-go/blob/5fe6fc56cb38d04ef4af601a03599c984229dea2/tools/clientcmd/client_config.go#L476
