### ISSUE TITLE
Bug: Panic on conflicting values in helm 2.3.0

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes/helm#2551]
I set in values.yaml
```
image: "foo"
```
and then on the `helm upgrade` command line [incorrectly] included:
```
--set image.repository="foo"
```
This is clearly an inconsistent configuration on my part, but it lead `helm` to panic rather than throwing an error.

```
Client: &version.Version{SemVer:"v2.3.0", GitCommit:"d83c245fc324117885ed83afc90ac74afed271b4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.3.0", GitCommit:"d83c245fc324117885ed83afc90ac74afed271b4", GitTreeState:"clean"}
```
```
Created tunnel using local port: '35794'
SERVER: "localhost:35794"
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
panic(0x16865a0, 0xc420013780)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/pkg/strvals.(*parser).key(0xc4205ef948, 0xc4202a8a80, 0x4391d8, 0x70)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/strvals/parser.go:133 +0x471
k8s.io/helm/pkg/strvals.(*parser).parse(0xc4205ef948, 0xc420416690, 0x6c)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/strvals/parser.go:76 +0x38
k8s.io/helm/pkg/strvals.ParseInto(0x7fff11b0241f, 0x6c, 0xc4202a8a80, 0x15af860, 0xc42009e6d0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/strvals/parser.go:60 +0xe8
main.(*upgradeCmd).vals(0xc4205b0270, 0x7fff11b023b7, 0x13, 0xc4200301f8, 0x1, 0x1)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/helm/upgrade.go:224 +0x409
main.(*upgradeCmd).run(0xc4205b0270, 0x0, 0x2193760)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/helm/upgrade.go:161 +0xd2
main.newUpgradeCmd.func1(0xc4204566c0, 0xc4202dac80, 0x2, 0x14, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/helm/upgrade.go:100 +0x126
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc4204566c0, 0xc4202daa00, 0x14, 0x14, 0xc4204566c0, 0xc4202daa00)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x234
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4204cd200, 0xc420425440, 0xc4203fc000, 0xc4203fcd80)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4204cd200, 0xc420030010, 0xc4204cd200)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/helm/helm.go:170 +0x47
```

**Comment by thomastaylor312** [comment]
@whereisaaron Does this bug also happen with the latest release (2.4.2 right now, 2.4.3 should be out tomorrow)?

**Comment by whereisaaron** [comment]
Thanks @thomastaylor312 I'll report back after I have the opportunity to update.

**Comment by technosophos** [comment]
Does this happen only on upgrade, or on install as well? I'm trying to reproduce locally on `master` and haven't yet. But I am not sure the bug was actually fixed.

**Comment by whereisaaron** [comment]
Thanks for looking into this, even though only a minor issue (exception vs fatal error).
Because I am automating helm, I only ever using `helm upgrade --install` so I don't have to work out whether a release already exists. My impression/guess, having caused a couple of other panics experimenting with `--set`, is that multiple `--set` arguments that are mutually incompatible/impossible can trigger the exception with 2.3, independent of anything else. If you are handling exceptions processing `--set` into the computed values in 2.4 then I'd expect that this issue is fixed.

**Comment by bacongobbler** [comment]
I'm going to close this ticket as it might've been fixed in a future release, but please re-open if this still needs to be addressed. Thanks!
