### ISSUE TITLE
helm package crashes if CHART_PATH doesn't exist

### ISSUE THREAD

**Issue by mparry** [kubernetes/helm#3209]
For example:

```bash
mkdir empty && cd empty
helm package not_there
```

This gives: 

```none
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x67fea9]

goroutine 1 [running]:
k8s.io/helm/pkg/chartutil.isSymlink(0x0, 0x0, 0xc0426cf988)
        c:/code/helm/src/k8s.io/helm/pkg/chartutil/load.go:325 +0x29
k8s.io/helm/pkg/chartutil.symWalk.func1(0xc0426f2be0, 0x1d, 0x0, 0x0, 0x20db480, 0xc042710360, 0x15b43e0, 0xc042710330)
        c:/code/helm/src/k8s.io/helm/pkg/chartutil/load.go:307 +0x96
path/filepath.Walk(0xc0426f2be0, 0x1d, 0xc042710330, 0x0, 0xc042710300)
        c:/users/m.parry/apps/go/src/path/filepath/path.go:401 +0x7d
k8s.io/helm/pkg/chartutil.LoadDir(0xc0426f2ba0, 0x1c, 0xc0426f2ba0, 0x1c, 0x0)
        c:/code/helm/src/k8s.io/helm/pkg/chartutil/load.go:282 +0x2d8
main.(*packageCmd).run(0xc0423d6e80, 0x1755688, 0x0)
        c:/code/helm/src/k8s.io/helm/cmd/helm/package.go:129 +0xa3
main.newPackageCmd.func1(0xc0421d6900, 0xc042342780, 0x1, 0x1, 0x0, 0x0)
        c:/code/helm/src/k8s.io/helm/cmd/helm/package.go:88 +0xdb
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc0421d6900, 0xc042342730, 0x1, 0x1, 0xc0421d6900, 0xc042342730)
        c:/code/helm/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3ef
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0423f4900, 0xc0424026c0, 0xc042402900, 0xc042403200)
        c:/code/helm/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x305
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0423f4900, 0x2, 0x3)
        c:/code/helm/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x32
main.main()
        c:/code/helm/src/k8s.io/helm/cmd/helm/helm.go:159 +0x7c
```

Expected result is:

```none
Error: GetFileAttributesEx C:\code\temp\empty\not_there\: The system cannot find the file specified.
```

I think this is due to the changes in #3113.

**Comment by bacongobbler** [comment]
#3113 was only recently merged so it's not in an official release yet. Which version of helm are you testing with?

**Comment by mparry** [comment]
Local build. I only opened the ticket so I could submit a PR. Or will #3195 mean that this doesn't need fixing (because it's going to change anyway)?

**Comment by bacongobbler** [comment]
You can give #3199 a shot and see if that fixes the issue!

**Comment by mparry** [comment]
Ah, ok, probably. (My fix was just to check `err` at the top of the old `symWalk()` function.)

I reckon this can just be closed then.

**Comment by bacongobbler** [comment]
Yeah, that case is likely covered by https://github.com/bacongobbler/helm/blob/6fff4f97cdbad5e18e66356f0851e45c2e60cc78/pkg/sympath/walk.go#L36-L45 so we can close this out once that PR is merged.
