### ISSUE TITLE
Tiller crashes when rendering a chart / on install

### ISSUE THREAD

**Issue by puco** [kubernetes/helm#3345]
When installing a new release from a chart Tiller pod crashes. As I'm currently debugging some new charts it is highly likely that there is some bug in the chart I'm currently developing. I also haven't managed to isolate a chart test case. But in any case I would expect to get an error what is wrong with the chart and not to crash the Tiller pod.

# Version info 

```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

# Repo steps

1.  In my custom chart `helm install --name=xyz --dry-run --debug .`

## Excepcted result

A new release created or an error what is wrong with the chart

## Actual result

Tiller crashes

```
[debug] Created tunnel using local port: '54181'

[debug] SERVER: "127.0.0.1:54181"

[debug] Original chart version: ""
[debug] CHART PATH: ***REDACTED***

Error: transport is closing
````

# Logs from Tiller:

```
> kubectl logs -n kube-system tiller-deploy-8696ff56d6-bbpw2 -f
[main] 2018/01/15 13:38:04 Starting Tiller v2.7.2 (tls=false)
[main] 2018/01/15 13:38:04 GRPC listening on :44134
[main] 2018/01/15 13:38:04 Probes listening on :44135
[main] 2018/01/15 13:38:04 Storage driver is ConfigMap
[main] 2018/01/15 13:38:04 Max history per release is 0
[tiller] 2018/01/15 13:52:25 preparing install for mpe
[storage] 2018/01/15 13:52:25 getting release history for "mpe"
[tiller] 2018/01/15 13:52:25 rendering XXXXX chart using values
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0xcde758]

goroutine 375 [running]:
text/template.errRecover(0xc420753098)
        /usr/local/go/src/text/template/exec.go:140 +0x1ec
panic(0x1564040, 0x21857a0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/helm/vendor/github.com/imdario/mergo.deepMerge(0x1555d00, 0xc42000c218, 0x195, 0x1555d00, 0xc420912900, 0x15, 0xc420751800, 0x0, 0xc420912900, 0x15)
        /go/src/k8s.io/helm/vendor/github.com/imdario/mergo/merge.go:49 +0x748
k8s.io/helm/vendor/github.com/imdario/mergo.Merge(0x14793a0, 0xc42000c218, 0x1555d00, 0xc420912900, 0x21a0d01, 0x7ffa1ed054b0)
        /go/src/k8s.io/helm/vendor/github.com/imdario/mergo/merge.go:98 +0x24b
k8s.io/helm/vendor/github.com/Masterminds/sprig.merge(0xc4209051a0, 0xc42000c210, 0x1, 0x1, 0x0, 0x0)
        /go/src/k8s.io/helm/vendor/github.com/Masterminds/sprig/dict.go:80 +0x99
reflect.Value.call(0x1514900, 0x17b2e80, 0x13, 0x172204d, 0x4, 0xc420924e10, 0x2, 0x2, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x1514900, 0x17b2e80, 0x13, 0xc420924e10, 0x2, 0x2, 0x2126560, 0xc42089fe00, 0x1555d00)
        /usr/local/go/src/reflect/value.go:302 +0xa4
text/template.(*state).evalCall(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0x1514900, 0x17b2e80, 0x13, 0x2126080, 0xc42089fd70, 0xc4201cd9ff, ...)
        /usr/local/go/src/text/template/exec.go:668 +0x51f
text/template.(*state).evalFunction(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0xc42089fda0, 0x2126080, 0xc42089fd70, 0xc4208a2700, 0x3, 0x4, ...)
        /usr/local/go/src/text/template/exec.go:536 +0x18e
text/template.(*state).evalCommand(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0xc42089fd70, 0x0, 0x0, 0x0, 0x2130701, 0x14c7da0, ...)
        /usr/local/go/src/text/template/exec.go:433 +0x6cd
text/template.(*state).evalPipeline(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0xc4208a6730, 0x14c7da0, 0x14c7da0, 0x10)
        /usr/local/go/src/text/template/exec.go:406 +0xf2
text/template.(*state).evalArg(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0x21307a0, 0x15186e0, 0x2126380, 0xc4208a6730, 0x1, 0xc4208eec20, ...)
        /usr/local/go/src/text/template/exec.go:746 +0x827
text/template.(*state).evalCall(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0x14ef240, 0x17b2b10, 0x13, 0x2126080, 0xc42089fd10, 0xc4201cd9f7, ...)
        /usr/local/go/src/text/template/exec.go:643 +0x279
text/template.(*state).evalFunction(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0xc42089fd40, 0x2126080, 0xc42089fd10, 0xc4208ce5e0, 0x2, 0x2, ...)
        /usr/local/go/src/text/template/exec.go:536 +0x18e
text/template.(*state).evalCommand(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0xc42089fd10, 0x0, 0x0, 0x0, 0x1555d00, 0xc42028a7d0, ...)
        /usr/local/go/src/text/template/exec.go:433 +0x6cd
text/template.(*state).evalPipeline(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0xc4208a66e0, 0x1555d00, 0xc42028a7d0, 0x95)
        /usr/local/go/src/text/template/exec.go:406 +0xf2
text/template.(*state).walk(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0x2125f00, 0xc42089fe30)
        /usr/local/go/src/text/template/exec.go:232 +0x55a
text/template.(*state).walk(0xc420752940, 0x1488340, 0xc4208ee528, 0x97, 0x2126260, 0xc42089f890)
        /usr/local/go/src/text/template/exec.go:240 +0x139
text/template.(*state).walkTemplate(0xc420752e48, 0x1488340, 0xc4208ee528, 0x97, 0xc42087f040)
        /usr/local/go/src/text/template/exec.go:389 +0x267
text/template.(*state).walk(0xc420752e48, 0x1488340, 0xc4208fffc8, 0x97, 0x21264a0, 0xc42087f040)
        /usr/local/go/src/text/template/exec.go:245 +0x226
text/template.(*state).walk(0xc420752e48, 0x1488340, 0xc4208fffc8, 0x97, 0x2126260, 0xc4208859e0)
        /usr/local/go/src/text/template/exec.go:240 +0x139
text/template.(*state).walkIfOrWith(0xc420752e48, 0xa, 0x1488340, 0xc4208fffc8, 0x97, 0xc4203eb680, 0xc4208859e0, 0x0)
        /usr/local/go/src/text/template/exec.go:270 +0x1c8
text/template.(*state).walk(0xc420752e48, 0x1488340, 0xc4208fffc8, 0x97, 0x2126200, 0xc42087f080)
        /usr/local/go/src/text/template/exec.go:237 +0x377
text/template.(*state).walk(0xc420752e48, 0x1488340, 0xc4208fffc8, 0x97, 0x2126260, 0xc420885920)
        /usr/local/go/src/text/template/exec.go:240 +0x139
text/template.(*state).walkIfOrWith(0xc420752e48, 0xa, 0x1488340, 0xc4208fffc8, 0x97, 0xc4203eb630, 0xc420885920, 0x0)
        /usr/local/go/src/text/template/exec.go:270 +0x1c8
text/template.(*state).walk(0xc420752e48, 0x1488340, 0xc4208fffc8, 0x97, 0x2126200, 0xc42087f0c0)
        /usr/local/go/src/text/template/exec.go:237 +0x377
text/template.(*state).walk(0xc420752e48, 0x1488340, 0xc4208fffc8, 0x97, 0x2126260, 0xc420885710)
        /usr/local/go/src/text/template/exec.go:240 +0x139
text/template.(*state).walkTemplate(0xc420753018, 0x1488340, 0xc4208fffc8, 0x97, 0xc420887b00)
        /usr/local/go/src/text/template/exec.go:389 +0x267
text/template.(*state).walk(0xc420753018, 0x1624cc0, 0xc420807740, 0x15, 0x21264a0, 0xc420887b00)
        /usr/local/go/src/text/template/exec.go:245 +0x226
text/template.(*state).walk(0xc420753018, 0x1624cc0, 0xc420807740, 0x15, 0x2126260, 0xc420898510)
        /usr/local/go/src/text/template/exec.go:240 +0x139
text/template.(*Template).execute(0xc420887a40, 0x2103040, 0xc42049c000, 0x1624cc0, 0xc420807740, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:195 +0x20a
text/template.(*Template).Execute(0xc420887a40, 0x2103040, 0xc42049c000, 0x1624cc0, 0xc420807740, 0xc4208fff01, 0xc42043d470)
        /usr/local/go/src/text/template/exec.go:178 +0x53
text/template.(*Template).ExecuteTemplate(0xc4208c6e00, 0x2103040, 0xc42049c000, 0xc42082a090, 0x2f, 0x1624cc0, 0xc420807740, 0xc420526800, 0x7b0)
        /usr/local/go/src/text/template/exec.go:165 +0x77
k8s.io/helm/pkg/engine.(*Engine).render(0xc4202b5a80, 0xc420806900, 0xc420806900, 0x21037c0, 0xc4202b5a80)
        /go/src/k8s.io/helm/pkg/engine/engine.go:244 +0xcc6
k8s.io/helm/pkg/engine.(*Engine).Render(0xc4202b5a80, 0xc420131b00, 0xc42076d410, 0xc4202b5a80, 0x1, 0xc4207a0e70)
        /go/src/k8s.io/helm/pkg/engine/engine.go:123 +0x6a
k8s.io/helm/pkg/tiller.(*ReleaseServer).renderResources(0xc420237440, 0xc420131b00, 0xc42076d410, 0xc42076d350, 0xc420218c40, 0xc42012dab6, 0x7, 0x100, 0x1, 0xc4202ffd00, ...)
        /go/src/k8s.io/helm/pkg/tiller/release_server.go:257 +0x197
k8s.io/helm/pkg/tiller.(*ReleaseServer).prepareRelease(0xc420237440, 0xc420131aa0, 0xc42012dc70, 0x1, 0x1)
        /go/src/k8s.io/helm/pkg/tiller/release_install.go:87 +0x21d
k8s.io/helm/pkg/tiller.(*ReleaseServer).InstallRelease(0xc420237440, 0x7ffa1ecae300, 0xc4202378f0, 0xc420131aa0, 0xc420237440, 0x1763e9d, 0xe)
        /go/src/k8s.io/helm/pkg/tiller/release_install.go:36 +0xff
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_InstallRelease_Handler.func1(0x7ffa1ecae300, 0xc4202378f0, 0x16871e0, 0xc420131aa0, 0x33, 0xc420012f50, 0x20, 0x18)
        /go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1218 +0x86
k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x7ffa1ecae300, 0xc4202378f0, 0x16871e0, 0xc420131aa0, 0xc4202670a0, 0xc4202670c0, 0xc4200c9540, 0xc42012d080, 0xc420731ad8, 0x40fdb8)
        /go/src/k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xad
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x7ffa1ecae300, 0xc4202378f0, 0x16871e0, 0xc420131aa0, 0xc4202670a0, 0xc4202670c0, 0x0, 0xc42061cb50, 0x40fdb8, 0x70)
        /go/src/k8s.io/helm/pkg/tiller/server.go:59 +0xb5
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_InstallRelease_Handler(0x16e62c0, 0xc420237440, 0x7ffa1ecae300, 0xc4202378f0, 0xc42049d260, 0x17b2c08, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1220 +0x177
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200c9500, 0x2127b20, 0xc4202f09a0, 0xc4201b2120, 0xc4202374d0, 0x218f948, 0xc4202379b0, 0x0, 0x0)
        /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:738 +0xaa0
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200c9500, 0x2127b20, 0xc4202f09a0, 0xc4201b2120, 0xc4202379b0)
        /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:932 +0x1339
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42012d010, 0xc4200c9500, 0x2127b20, 0xc4202f09a0, 0xc4201b2120)
        /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:497 +0xa9
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:498 +0xa1
```

**Comment by bacongobbler** [comment]
Hey @puco! This bug report looks identical to https://github.com/kubernetes/helm/issues/3290. We are going to close this one in favour of the opther issue so wwe can track bugs/discussion all in one ticket. Would you mind following up over there? Thank you!
