### ISSUE TITLE
helm dep manifest and helm dep config panic

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#481]
After attempting to deploy a chart (the resourcification failed, but that shouldn't matter), curl shows the deployment and manifest:

```
jackgr@jackgr-macbookpro:~/gopath/src/github.com/kubernetes/helm> helm deploy --name test2 examples/charts/replicatedservice
[ERROR] {"status":"Bad Request","message":"Found resource errors during deployment: [kubectl failed error: you must provide one or more resources by argument or filename (.json|.stdin|.yaml|.yml)\n]"}

jackgr@jackgr-macbookpro:~/gopath/src/github.com/kubernetes/helm> curl localhost:8080/deployments/test2/manifests["manifest-1459277758117753368"]

jackgr@jackgr-macbookpro:~/gopath/src/github.com/kubernetes/helm> curl localhost:8080/deployments/test2/manifests/manifest-1459277758117753368
{"deployment":"test2","name":"manifest-1459277758117753368","inputConfig":{"resources":[{"name":"test2","type":"examples/charts/replicatedservice"}]},"expandedConfig":{"resources":[{"name":"test2","type":"examples/charts/replicatedservice"}]},"layout":{"resources":[{"name":"test2","type":"examples/charts/replicatedservice"}]}}
```

but `helm dep manifest` and `helm dep config` panic:

```
jackgr@jackgr-macbookpro:~/gopath/src/github.com/kubernetes/helm> helm dep manifest test2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7260e]

goroutine 1 [running]:
github.com/codegangsta/cli.Command.Run(0x457e70, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4c1170, 0x36, 0x0, ...)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/command.go:174 +0x13fe
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc208080500, 0xc2080803c0, 0x0, 0x0)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/app.go:298 +0x115c
github.com/codegangsta/cli.Command.startApp(0x452e50, 0xa, 0x0, 0x0, 0xc20802a920, 0x1, 0x1, 0x4a20f0, 0x27, 0x0, ...)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/command.go:249 +0x74f
github.com/codegangsta/cli.Command.Run(0x452e50, 0xa, 0x0, 0x0, 0xc20802a920, 0x1, 0x1, 0x4a20f0, 0x27, 0x0, ...)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/command.go:65 +0xb1
github.com/codegangsta/cli.(*App).Run(0xc208080280, 0xc20800a000, 0x4, 0x4, 0x0, 0x0)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/app.go:187 +0x1221
main.main()
	/Users/jackgr/gopath/src/github.com/kubernetes/helm/cmd/helm/helm.go:91 +0x3b8

jackgr@jackgr-macbookpro:~/gopath/src/github.com/kubernetes/helm> helm dep config test2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7260e]

goroutine 1 [running]:
github.com/codegangsta/cli.Command.Run(0x42fa30, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4c11d0, 0x30, 0x0, ...)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/command.go:174 +0x13fe
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc208080500, 0xc2080803c0, 0x0, 0x0)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/app.go:298 +0x115c
github.com/codegangsta/cli.Command.startApp(0x452e50, 0xa, 0x0, 0x0, 0xc20802a920, 0x1, 0x1, 0x4a20f0, 0x27, 0x0, ...)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/command.go:249 +0x74f
github.com/codegangsta/cli.Command.Run(0x452e50, 0xa, 0x0, 0x0, 0xc20802a920, 0x1, 0x1, 0x4a20f0, 0x27, 0x0, ...)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/command.go:65 +0xb1
github.com/codegangsta/cli.(*App).Run(0xc208080280, 0xc20800a000, 0x4, 0x4, 0x0, 0x0)
	/Users/jackgr/gopath/src/github.com/codegangsta/cli/app.go:187 +0x1221
main.main()
	/Users/jackgr/gopath/src/github.com/kubernetes/helm/cmd/helm/helm.go:91 +0x3b8

```

**Comment by technosophos** [comment]
These are not in MVP, so should be removed.
